### PR TITLE
Milestone 4: Game Instructions and README.md improvement

### PR DESCRIPTION
**Pull request by ldelbel**
Greetings, 

- [ ] We added feature branch named readme_game_instrutions
- [ ] Added game instructions in README.md file
- [ ] Added the live demo link to the README.md file, pointing to repl.it website
- [ ] Added Setup and installing instructions to README.md file 

Kindly request a pull request to merge our feature branch to the development branch and we thank you in advance for your support.

### CODE REVIEW

**Review by adaorachi — CHANGES_REQUESTED** [review]
## **Hi team, 👋** 

Good Job on the completion of the first draft of this milestone. Your game is very interactive and the implementation of the game's different levels was impressive. I like it. Well done! 👍 💯
However, you'll need to implement a couple of changes to the content of the README file to make it very explanatory and professional.

---
### **CHANGES REQUIRED** ♻️ 

---

- [ ] The functionality for your game looks great and I would also like to see detailed instructions on how to play it. In the README file, the instructions look somewhat ambiguous and not easily understood. For example, in this instruction- "_The game is played on a grid that's 3 to 5 squares by 3 to 5 squares._", it should be very well explained that the game has different levels - _a 3x3, 4x4 and 5x5 square game levels_.

- [ ] Still in the README content, this instruction - "_The first player to get 3 to 5 of her marks in a row_". This means what it is literally, that is, -  _the first person to place his/her marker in 3 to 5 places in a row_ -  and which is not how the game is played. In this case, you should make it explanatory like this - the first player to place 3 of his/her marker in a 3 by 3 game level OR to place 4 of his/her marker in a 4 by 4 game level ...

- [ ] This is a collaborative project and it is required that both collaborators are engaged in this project by making equal numbers of commits. Kindly ensure this is adhered to in subsequent collaborations.

### **The requirements below are considered optional, but I encourage you to take a look at it.**

- [**optional**]  You should consider adding one or two screenshots. This aids visual representation.

- [**optional**] In the part of the gameplay shown in the screenshot below, you should consider highlighting the different game levels there. For example - Enter 3 for a 3x3 game level. Enter 4 for a 4x4 game level. Enter 5 for a 5x5 game level.
Or instead of the 3x3 game level...etc, you can term the levels - Easy, Medium, Hard. This is to enhance the user experience of your game and make the instructions easy to understand.

Annotation 2020-06-30 164008


---
**After implementing the mandatory changes above, you can request for another review by submitting a code review form.
Note: All requirements not marked with **optional** are mandatory.**

Should you have any questions, please reach out to me on Slack with the username **@adaorachi**.

Happy Coding ☺️ 

**MaryAnn Chukwuka**

**Comment by temesghentekeste** [comment]
Thanks for your feedback. We have fixed the issues as per your suggestions. Kindly request another code review before we merge our feature branch to the development branch.

**Review by mosesogwo — APPROVED** [review]
**Your game description now looks great:+1:. Milestone is approved**

You can now merge this pull request.

_**Cheers :stars:**_

### Status: Approved :heavy_check_mark:

**Comment by temesghentekeste** [comment]
Thanks @mosesogwo for approving the project.

**Pull request merged**
